### ISSUE TITLE
图片存放问题

### ISSUE THREAD

**Issue by l0n3rs** [Undertone0809/md-img-converter#1]
请问图片能否直接存放本地，使用本地相对路径？

**Comment by Undertone0809** [comment]
ok，我改一改结构增加一个本地路径替换的选择

**Comment by l0n3rs** [comment]
> ok，我改一改结构增加一个本地路径替换的选择

感谢师傅！！

**Comment by Undertone0809** [comment]
@l0n3rs 已经更新了一个版本#2 ，如果对你有帮助的话欢迎star！有其他的建议也可以告诉我。
