### ISSUE TITLE
你这个教程里面有些东西看不懂，我看完教程后还是不知道该怎样操作。而且你说的config.yaml是哪里的yaml，你可以展示一下文件的路径

### ISSUE THREAD

**Issue by luanshang** [Undertone0809/md-img-converter#15]
## Checklist

- [ ] I've searched the project's [`issues`](https://github.com/Undertone0809/imarkdown/issues?q=is%3Aissue).

## ❓ Question

How can I [...]?

Is it possible to [...]?

**Comment by Undertone0809** [comment]
你看的应该是以前旧版本的博客了吧？imarkdown现在更新了新版本，现在的版本不再默认使用 config.yaml 作为配置文件了，也不再维护以前的版本了，可以参考最新版本的README进行上手
